[package]
name = "FeedbackControl"
version = "0.1.0"
authors = ["Huang Hao <shidephen@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmath = "0.2.1"
rand="0.8.4"
plotters = "0.3.1"